version: '3.7'

services:
  node-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/home/node/src
      - ./test:/home/node/test
    ports:
      - 3000:3000
    entrypoint: /bin/ash
