FROM node:10.16-alpine AS app

USER node
WORKDIR /home/node
COPY package.json package-lock.json /home/node/
RUN npm install

COPY .env /home/node/
COPY src /home/node/src
COPY test /home/node/test
COPY jest.config.js /home/node/
COPY tsconfig.json /home/node/

ENV NODE_ENV production

EXPOSE 3000
CMD ["npm", "run", "build"]
